In [36]:
#Number 8
from numpy import linalg as LA
import numpy as np
A = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print (LA.matrix_power(A,3))

[[ 225  450  675  900 1125]
 [ 225  450  675  900 1125]
 [ 225  450  675  900 1125]
 [ 225  450  675  900 1125]
 [ 225  450  675  900 1125]]


In [46]:
#Number 9
from sympy import *
A = Matrix([[2,4,5], [2,6,1], [-2,9,15], [12,0,15], [3,34,-52]])
B = Matrix([[2,4,5,4],[2,6,1,4],[-2,9,15,4]])
C = A*B
print (C.transpose())

Matrix([[2, 14, -16, -6, 178], [77, 53, 181, 183, -252], [89, 31, 224, 285, -731], [44, 36, 88, 108, -60]])


In [39]:
#Number 10
from numpy import linalg as LA
import numpy as np
M = np.array([[2,4,5], [2,6,1], [-2,9,15], [12,0,15], [3, 34, -52]])
print (LA.matrix_rank(M))


3


In [44]:
#Number 11
from sympy import *
import numpy as np
M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7],[-1, -3, -3, -4]])
print (M.rref())

(Matrix([
[1, 0,   1,   3],
[0, 1, 2/3, 1/3],
[0, 0,   0,   0]]), [0, 1])
